ethereum-node:
   image: parity/parity:stable
   container_name: parity
   command: --jsonrpc-interface all --ui-interface all --chain dev --ui-hosts=all 
   ports:
     - "8180:8180"
     - "8545:8545"
     - "8546:8546"
     - "30303:30303"
   volumes:
     - ~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/
